default_stages: [commit]

repos:
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v8.0.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ["@commitlint/config-angular"]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-yaml
      - id: check-json
  - repo: https://github.com/hadolint/hadolint
    rev: v2.8.0
    hooks:
      - id: hadolint-docker
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.14.0
    hooks:
      - id: eslint
        files: \.([jt]s|graphql)$
        types: [file]
        additional_dependencies:
          - "@typescript-eslint/eslint-plugin@^5.20.0"
          - "@typescript-eslint/parser@^5.20.0"
          - "eslint@^8.14.0"
          - "eslint-config-prettier@^8.5.0"
          - "eslint-plugin-import@^2.26.0"
          - "eslint-plugin-jest@^26.1.5"
          - "eslint-plugin-jest-formatting@^3.1.0"
          - "eslint-plugin-prettier@^4.0.0"
          - "eslint-plugin-simple-import-sort@^7.0.0"
          - "eslint-plugin-sonarjs@^0.13.0"
          - "eslint-plugin-tsdoc@^0.2.16"
          - "jest@^27.5.1"
          - "prettier@^2.6.2"
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.6.2
    hooks:
      - id: prettier
  - repo: https://github.com/keith/pre-commit-buildifier
    rev: 5.1.0.1
    hooks:
      - id: buildifier
      - id: buildifier-lint
